version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 1
  versioning-strategy: increase
  ignore:
  - dependency-name: lodash
    versions:
    - 4.17.20
- package-ecosystem: npm
  directory: "/examples/transform-amd-to-commonjs-example"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 1
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.4
    - 5.33.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
